server:
  port: 8888

spring:
  application:
    name: ssp-config
  cloud:
    config:
      enabled: true
      server:
        svn:
          uri: https://github.com/dev086/test.git
          username: dev086
          password: q1119859961
        #git:
        #  uri: https://github.com/pcf-guides/configuration-server-config-repo
        default-label: config
  profiles:
    active: subversion

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG
